### ISSUE TITLE
ServingTime String 리소스로 텍스트뷰에 전달하기

### ISSUE THREAD

**Issue by hongbeomi** [develop-playground/jeju-road-android#30]
- 리소스로 전달해달라는 경고가 띄워짐
- getString으로 가져오기

<img width="980" alt="image" src="https://user-images.githubusercontent.com/40753104/162413460-598b029a-cdb9-411f-aaf2-d9ef39c89f99.png">

**Comment by junhyung0927** [comment]
해결한거는 이슈 닫겠습니다~
